// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: account/proto/account_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_account_proto_account_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRequest) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type CreateAcocuntResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAcocuntResponse) Reset() {
	*x = CreateAcocuntResponse{}
	mi := &file_account_proto_account_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAcocuntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAcocuntResponse) ProtoMessage() {}

func (x *CreateAcocuntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAcocuntResponse.ProtoReflect.Descriptor instead.
func (*CreateAcocuntResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAcocuntResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateAcocuntResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateAcocuntResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

var File_account_proto_account_service_proto protoreflect.FileDescriptor

const file_account_proto_account_service_proto_rawDesc = "" +
	"\n" +
	"#account/proto/account_service.proto\"I\n" +
	"\x14CreateAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\"d\n" +
	"\x15CreateAcocuntResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId2R\n" +
	"\x0eAccountService\x12@\n" +
	"\rCreateAccount\x12\x15.CreateAccountRequest\x1a\x16.CreateAcocuntResponse\"\x00B\tZ\a./protob\x06proto3"

var (
	file_account_proto_account_service_proto_rawDescOnce sync.Once
	file_account_proto_account_service_proto_rawDescData []byte
)

func file_account_proto_account_service_proto_rawDescGZIP() []byte {
	file_account_proto_account_service_proto_rawDescOnce.Do(func() {
		file_account_proto_account_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_account_service_proto_rawDesc), len(file_account_proto_account_service_proto_rawDesc)))
	})
	return file_account_proto_account_service_proto_rawDescData
}

var file_account_proto_account_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_proto_account_service_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),  // 0: CreateAccountRequest
	(*CreateAcocuntResponse)(nil), // 1: CreateAcocuntResponse
}
var file_account_proto_account_service_proto_depIdxs = []int32{
	0, // 0: AccountService.CreateAccount:input_type -> CreateAccountRequest
	1, // 1: AccountService.CreateAccount:output_type -> CreateAcocuntResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_proto_account_service_proto_init() }
func file_account_proto_account_service_proto_init() {
	if File_account_proto_account_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_account_service_proto_rawDesc), len(file_account_proto_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_proto_account_service_proto_goTypes,
		DependencyIndexes: file_account_proto_account_service_proto_depIdxs,
		MessageInfos:      file_account_proto_account_service_proto_msgTypes,
	}.Build()
	File_account_proto_account_service_proto = out.File
	file_account_proto_account_service_proto_goTypes = nil
	file_account_proto_account_service_proto_depIdxs = nil
}
