// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: account/proto/account_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     []byte                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	UserId        []byte                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_account_proto_account_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *Account) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *Account) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   []byte                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccountId       []byte                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount          int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp       int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TransactionType []byte                 `protobuf:"bytes,5,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"` // "credit" or "debit"
	Status          []byte                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                          // "pending", "completed", "failed"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_account_proto_account_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetTransactionId() []byte {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

func (x *Transaction) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetTransactionType() []byte {
	if x != nil {
		return x.TransactionType
	}
	return nil
}

func (x *Transaction) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []byte                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	ReqUserId     []byte                 `protobuf:"bytes,5,opt,name=req_user_id,json=reqUserId,proto3" json:"req_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_account_proto_account_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *CreateAccountRequest) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *CreateAccountRequest) GetReqUserId() []byte {
	if x != nil {
		return x.ReqUserId
	}
	return nil
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         []byte                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	AccountId     []byte                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_account_proto_account_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateAccountResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CreateAccountResponse) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

// I think AddToAccountBalance is clearer than UpdateAccountBalance cause Update can mean "set" it to this amount instead of adding/substracting to it
type UpdateAccountBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []byte                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     []byte                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	ReqUserId     []byte                 `protobuf:"bytes,5,opt,name=req_user_id,json=reqUserId,proto3" json:"req_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountBalanceRequest) Reset() {
	*x = UpdateAccountBalanceRequest{}
	mi := &file_account_proto_account_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountBalanceRequest) ProtoMessage() {}

func (x *UpdateAccountBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountBalanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountBalanceRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAccountBalanceRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *UpdateAccountBalanceRequest) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *UpdateAccountBalanceRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *UpdateAccountBalanceRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateAccountBalanceRequest) GetReqUserId() []byte {
	if x != nil {
		return x.ReqUserId
	}
	return nil
}

type UpdateAccountBalanceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error          []byte                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	UpdatedBalance int64                  `protobuf:"varint,3,opt,name=updated_balance,json=updatedBalance,proto3" json:"updated_balance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAccountBalanceResponse) Reset() {
	*x = UpdateAccountBalanceResponse{}
	mi := &file_account_proto_account_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountBalanceResponse) ProtoMessage() {}

func (x *UpdateAccountBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountBalanceResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountBalanceResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAccountBalanceResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateAccountBalanceResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *UpdateAccountBalanceResponse) GetUpdatedBalance() int64 {
	if x != nil {
		return x.UpdatedBalance
	}
	return 0
}

type GetAccountsByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []byte                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReqUserId     []byte                 `protobuf:"bytes,5,opt,name=req_user_id,json=reqUserId,proto3" json:"req_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsByUserIdRequest) Reset() {
	*x = GetAccountsByUserIdRequest{}
	mi := &file_account_proto_account_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsByUserIdRequest) ProtoMessage() {}

func (x *GetAccountsByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetAccountsByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountsByUserIdRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *GetAccountsByUserIdRequest) GetReqUserId() []byte {
	if x != nil {
		return x.ReqUserId
	}
	return nil
}

type GetAccountsByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         []byte                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Accounts      []*Account             `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsByUserIdResponse) Reset() {
	*x = GetAccountsByUserIdResponse{}
	mi := &file_account_proto_account_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsByUserIdResponse) ProtoMessage() {}

func (x *GetAccountsByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetAccountsByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountsByUserIdResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetAccountsByUserIdResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetAccountsByUserIdResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type GetAccountByAccountNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber int64                  `protobuf:"varint,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	UserId        []byte                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReqUserId     []byte                 `protobuf:"bytes,5,opt,name=req_user_id,json=reqUserId,proto3" json:"req_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByAccountNumberRequest) Reset() {
	*x = GetAccountByAccountNumberRequest{}
	mi := &file_account_proto_account_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByAccountNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByAccountNumberRequest) ProtoMessage() {}

func (x *GetAccountByAccountNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByAccountNumberRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByAccountNumberRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetAccountByAccountNumberRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *GetAccountByAccountNumberRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *GetAccountByAccountNumberRequest) GetReqUserId() []byte {
	if x != nil {
		return x.ReqUserId
	}
	return nil
}

type GetAccountByAccountNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         []byte                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Account       *Account               `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByAccountNumberResponse) Reset() {
	*x = GetAccountByAccountNumberResponse{}
	mi := &file_account_proto_account_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByAccountNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByAccountNumberResponse) ProtoMessage() {}

func (x *GetAccountByAccountNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByAccountNumberResponse.ProtoReflect.Descriptor instead.
func (*GetAccountByAccountNumberResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetAccountByAccountNumberResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetAccountByAccountNumberResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetAccountByAccountNumberResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type DeleteAccountByAccountNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber int64                  `protobuf:"varint,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	UserId        []byte                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReqUserId     []byte                 `protobuf:"bytes,5,opt,name=req_user_id,json=reqUserId,proto3" json:"req_user_id,omitempty"`
	IdempotentKey []byte                 `protobuf:"bytes,3,opt,name=idempotent_key,json=idempotentKey,proto3" json:"idempotent_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountByAccountNumberRequest) Reset() {
	*x = DeleteAccountByAccountNumberRequest{}
	mi := &file_account_proto_account_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountByAccountNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountByAccountNumberRequest) ProtoMessage() {}

func (x *DeleteAccountByAccountNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountByAccountNumberRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountByAccountNumberRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAccountByAccountNumberRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *DeleteAccountByAccountNumberRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *DeleteAccountByAccountNumberRequest) GetReqUserId() []byte {
	if x != nil {
		return x.ReqUserId
	}
	return nil
}

func (x *DeleteAccountByAccountNumberRequest) GetIdempotentKey() []byte {
	if x != nil {
		return x.IdempotentKey
	}
	return nil
}

type DeleteAccountByAccountNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         []byte                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountByAccountNumberResponse) Reset() {
	*x = DeleteAccountByAccountNumberResponse{}
	mi := &file_account_proto_account_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountByAccountNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountByAccountNumberResponse) ProtoMessage() {}

func (x *DeleteAccountByAccountNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountByAccountNumberResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountByAccountNumberResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAccountByAccountNumberResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteAccountByAccountNumberResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

type CreateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          []byte                 `protobuf:"bytes,51,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId       []byte                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	IdempotentKey   []byte                 `protobuf:"bytes,3,opt,name=idempotent_key,json=idempotentKey,proto3" json:"idempotent_key,omitempty"` // to prevent double spending
	Amount          int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionType []byte                 `protobuf:"bytes,5,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"` // "CREDIT" or "DEBIT" or "TRANSFER_CREDIT" or "TRANSFER_DEBIT"
	TransferId      []byte                 `protobuf:"bytes,6,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`                // for transfer transactions, this is the id of the other transaction
	Status          []byte                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                                          // "pending", "completed", "failed"
	ReqUserId       []byte                 `protobuf:"bytes,8,opt,name=req_user_id,json=reqUserId,proto3" json:"req_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_account_proto_account_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTransactionRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *CreateTransactionRequest) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *CreateTransactionRequest) GetIdempotentKey() []byte {
	if x != nil {
		return x.IdempotentKey
	}
	return nil
}

func (x *CreateTransactionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetTransactionType() []byte {
	if x != nil {
		return x.TransactionType
	}
	return nil
}

func (x *CreateTransactionRequest) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *CreateTransactionRequest) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateTransactionRequest) GetReqUserId() []byte {
	if x != nil {
		return x.ReqUserId
	}
	return nil
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         []byte                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	TransactionId []byte                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_account_proto_account_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTransactionResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateTransactionResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CreateTransactionResponse) GetTransactionId() []byte {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

type GetTransactionsByAccountIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     []byte                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        []byte                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReqUserId     []byte                 `protobuf:"bytes,5,opt,name=req_user_id,json=reqUserId,proto3" json:"req_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByAccountIdRequest) Reset() {
	*x = GetTransactionsByAccountIdRequest{}
	mi := &file_account_proto_account_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByAccountIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByAccountIdRequest) ProtoMessage() {}

func (x *GetTransactionsByAccountIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByAccountIdRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsByAccountIdRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetTransactionsByAccountIdRequest) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *GetTransactionsByAccountIdRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *GetTransactionsByAccountIdRequest) GetReqUserId() []byte {
	if x != nil {
		return x.ReqUserId
	}
	return nil
}

type GetTransactionsByAccountIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         []byte                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByAccountIdResponse) Reset() {
	*x = GetTransactionsByAccountIdResponse{}
	mi := &file_account_proto_account_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByAccountIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByAccountIdResponse) ProtoMessage() {}

func (x *GetTransactionsByAccountIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByAccountIdResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsByAccountIdResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetTransactionsByAccountIdResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetTransactionsByAccountIdResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetTransactionsByAccountIdResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_account_proto_account_service_proto protoreflect.FileDescriptor

const file_account_proto_account_service_proto_rawDesc = "" +
	"\n" +
	"#account/proto/account_service.proto\"\x82\x01\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\fR\taccountId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\fR\x06userId\"\xcc\x01\n" +
	"\vTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\fR\rtransactionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\fR\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12)\n" +
	"\x10transaction_type\x18\x05 \x01(\fR\x0ftransactionType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\fR\x06status\"i\n" +
	"\x14CreateAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\fR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x12\x1e\n" +
	"\vreq_user_id\x18\x05 \x01(\fR\treqUserId\"d\n" +
	"\x15CreateAccountResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\fR\x05error\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\fR\taccountId\"\xb4\x01\n" +
	"\x1bUpdateAccountBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\fR\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\fR\taccountId\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\x03R\raccountNumber\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1e\n" +
	"\vreq_user_id\x18\x05 \x01(\fR\treqUserId\"u\n" +
	"\x1cUpdateAccountBalanceResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\fR\x05error\x12'\n" +
	"\x0fupdated_balance\x18\x03 \x01(\x03R\x0eupdatedBalance\"U\n" +
	"\x1aGetAccountsByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\fR\x06userId\x12\x1e\n" +
	"\vreq_user_id\x18\x05 \x01(\fR\treqUserId\"q\n" +
	"\x1bGetAccountsByUserIdResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\fR\x05error\x12$\n" +
	"\baccounts\x18\x03 \x03(\v2\b.AccountR\baccounts\"\x82\x01\n" +
	" GetAccountByAccountNumberRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\x03R\raccountNumber\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\fR\x06userId\x12\x1e\n" +
	"\vreq_user_id\x18\x05 \x01(\fR\treqUserId\"u\n" +
	"!GetAccountByAccountNumberResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\fR\x05error\x12\"\n" +
	"\aaccount\x18\x03 \x01(\v2\b.AccountR\aaccount\"\xac\x01\n" +
	"#DeleteAccountByAccountNumberRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\x03R\raccountNumber\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\fR\x06userId\x12\x1e\n" +
	"\vreq_user_id\x18\x05 \x01(\fR\treqUserId\x12%\n" +
	"\x0eidempotent_key\x18\x03 \x01(\fR\ridempotentKey\"T\n" +
	"$DeleteAccountByAccountNumberResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\fR\x05error\"\x95\x02\n" +
	"\x18CreateTransactionRequest\x12\x17\n" +
	"\auser_id\x183 \x01(\fR\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\fR\taccountId\x12%\n" +
	"\x0eidempotent_key\x18\x03 \x01(\fR\ridempotentKey\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12)\n" +
	"\x10transaction_type\x18\x05 \x01(\fR\x0ftransactionType\x12\x1f\n" +
	"\vtransfer_id\x18\x06 \x01(\fR\n" +
	"transferId\x12\x16\n" +
	"\x06status\x18\a \x01(\fR\x06status\x12\x1e\n" +
	"\vreq_user_id\x18\b \x01(\fR\treqUserId\"p\n" +
	"\x19CreateTransactionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\fR\x05error\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\fR\rtransactionId\"{\n" +
	"!GetTransactionsByAccountIdRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\fR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\fR\x06userId\x12\x1e\n" +
	"\vreq_user_id\x18\x05 \x01(\fR\treqUserId\"\x84\x01\n" +
	"\"GetTransactionsByAccountIdResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\fR\x05error\x120\n" +
	"\ftransactions\x18\x03 \x03(\v2\f.TransactionR\ftransactions2\xdd\x02\n" +
	"\x0eAccountService\x12@\n" +
	"\rCreateAccount\x12\x15.CreateAccountRequest\x1a\x16.CreateAccountResponse\"\x00\x12R\n" +
	"\x13GetAccountsByUserId\x12\x1b.GetAccountsByUserIdRequest\x1a\x1c.GetAccountsByUserIdResponse\"\x00\x12L\n" +
	"\x11CreateTransaction\x12\x19.CreateTransactionRequest\x1a\x1a.CreateTransactionResponse\"\x00\x12g\n" +
	"\x1aGetTransactionsByAccountId\x12\".GetTransactionsByAccountIdRequest\x1a#.GetTransactionsByAccountIdResponse\"\x00B\tZ\a./protob\x06proto3"

var (
	file_account_proto_account_service_proto_rawDescOnce sync.Once
	file_account_proto_account_service_proto_rawDescData []byte
)

func file_account_proto_account_service_proto_rawDescGZIP() []byte {
	file_account_proto_account_service_proto_rawDescOnce.Do(func() {
		file_account_proto_account_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_account_service_proto_rawDesc), len(file_account_proto_account_service_proto_rawDesc)))
	})
	return file_account_proto_account_service_proto_rawDescData
}

var file_account_proto_account_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_account_proto_account_service_proto_goTypes = []any{
	(*Account)(nil),                              // 0: Account
	(*Transaction)(nil),                          // 1: Transaction
	(*CreateAccountRequest)(nil),                 // 2: CreateAccountRequest
	(*CreateAccountResponse)(nil),                // 3: CreateAccountResponse
	(*UpdateAccountBalanceRequest)(nil),          // 4: UpdateAccountBalanceRequest
	(*UpdateAccountBalanceResponse)(nil),         // 5: UpdateAccountBalanceResponse
	(*GetAccountsByUserIdRequest)(nil),           // 6: GetAccountsByUserIdRequest
	(*GetAccountsByUserIdResponse)(nil),          // 7: GetAccountsByUserIdResponse
	(*GetAccountByAccountNumberRequest)(nil),     // 8: GetAccountByAccountNumberRequest
	(*GetAccountByAccountNumberResponse)(nil),    // 9: GetAccountByAccountNumberResponse
	(*DeleteAccountByAccountNumberRequest)(nil),  // 10: DeleteAccountByAccountNumberRequest
	(*DeleteAccountByAccountNumberResponse)(nil), // 11: DeleteAccountByAccountNumberResponse
	(*CreateTransactionRequest)(nil),             // 12: CreateTransactionRequest
	(*CreateTransactionResponse)(nil),            // 13: CreateTransactionResponse
	(*GetTransactionsByAccountIdRequest)(nil),    // 14: GetTransactionsByAccountIdRequest
	(*GetTransactionsByAccountIdResponse)(nil),   // 15: GetTransactionsByAccountIdResponse
}
var file_account_proto_account_service_proto_depIdxs = []int32{
	0,  // 0: GetAccountsByUserIdResponse.accounts:type_name -> Account
	0,  // 1: GetAccountByAccountNumberResponse.account:type_name -> Account
	1,  // 2: GetTransactionsByAccountIdResponse.transactions:type_name -> Transaction
	2,  // 3: AccountService.CreateAccount:input_type -> CreateAccountRequest
	6,  // 4: AccountService.GetAccountsByUserId:input_type -> GetAccountsByUserIdRequest
	12, // 5: AccountService.CreateTransaction:input_type -> CreateTransactionRequest
	14, // 6: AccountService.GetTransactionsByAccountId:input_type -> GetTransactionsByAccountIdRequest
	3,  // 7: AccountService.CreateAccount:output_type -> CreateAccountResponse
	7,  // 8: AccountService.GetAccountsByUserId:output_type -> GetAccountsByUserIdResponse
	13, // 9: AccountService.CreateTransaction:output_type -> CreateTransactionResponse
	15, // 10: AccountService.GetTransactionsByAccountId:output_type -> GetTransactionsByAccountIdResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_account_proto_account_service_proto_init() }
func file_account_proto_account_service_proto_init() {
	if File_account_proto_account_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_account_service_proto_rawDesc), len(file_account_proto_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_proto_account_service_proto_goTypes,
		DependencyIndexes: file_account_proto_account_service_proto_depIdxs,
		MessageInfos:      file_account_proto_account_service_proto_msgTypes,
	}.Build()
	File_account_proto_account_service_proto = out.File
	file_account_proto_account_service_proto_goTypes = nil
	file_account_proto_account_service_proto_depIdxs = nil
}
