// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: account.proto

package proto

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Account) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *Account) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccountId       string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount          int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp       int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TransactionType string                 `protobuf:"bytes,5,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"` // "CREDIT" or "DEBIT" or "TRANSFER_CREDIT" or "TRANSFER_DEBIT"
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                          // "PENDING", "COMPLETED", "FAILED"
	TransferId      string                 `protobuf:"bytes,7,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`                // for transfer transactions, this is the id of the other transaction
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Transaction) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

// user_id is the ID of the user associated with the JWT token validated at the API Gateway
type CreateAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance        int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRequest) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *CreateAccountRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// user_id is the ID of the user associated with the JWT token validated at the API Gateway
type GetAccountsByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsByUserIdRequest) Reset() {
	*x = GetAccountsByUserIdRequest{}
	mi := &file_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsByUserIdRequest) ProtoMessage() {}

func (x *GetAccountsByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetAccountsByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountsByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAccountsByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsByUserIdResponse) Reset() {
	*x = GetAccountsByUserIdResponse{}
	mi := &file_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsByUserIdResponse) ProtoMessage() {}

func (x *GetAccountsByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetAccountsByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountsByUserIdResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

// user_id is the ID of the user associated with the JWT token validated at the API Gateway
type GetAccountByAccountNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByAccountNumberRequest) Reset() {
	*x = GetAccountByAccountNumberRequest{}
	mi := &file_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByAccountNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByAccountNumberRequest) ProtoMessage() {}

func (x *GetAccountByAccountNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByAccountNumberRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByAccountNumberRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountByAccountNumberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAccountByAccountNumberRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

type GetAccountByAccountNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByAccountNumberResponse) Reset() {
	*x = GetAccountByAccountNumberResponse{}
	mi := &file_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByAccountNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByAccountNumberResponse) ProtoMessage() {}

func (x *GetAccountByAccountNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByAccountNumberResponse.ProtoReflect.Descriptor instead.
func (*GetAccountByAccountNumberResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountByAccountNumberResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

// user_id is the ID of the user associated with the JWT token validated at the API Gateway
type DeleteAccountByAccountNumberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountNumber  int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteAccountByAccountNumberRequest) Reset() {
	*x = DeleteAccountByAccountNumberRequest{}
	mi := &file_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountByAccountNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountByAccountNumberRequest) ProtoMessage() {}

func (x *DeleteAccountByAccountNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountByAccountNumberRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountByAccountNumberRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAccountByAccountNumberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteAccountByAccountNumberRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *DeleteAccountByAccountNumberRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type DeleteAccountByAccountNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountByAccountNumberResponse) Reset() {
	*x = DeleteAccountByAccountNumberResponse{}
	mi := &file_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountByAccountNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountByAccountNumberResponse) ProtoMessage() {}

func (x *DeleteAccountByAccountNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountByAccountNumberResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountByAccountNumberResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{9}
}

// user_id is the ID of the user associated with the JWT token validated at the API Gateway
type CreateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId       string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount          int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionType string                 `protobuf:"bytes,4,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"` // "CREDIT" or "DEBIT" or "TRANSFER_CREDIT" or "TRANSFER_DEBIT"
	TransferId      string                 `protobuf:"bytes,5,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`                // for transfer transactions, this is the id of the other transaction
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                          // "PENDING", "COMPLETED", "FAILED"
	IdempotencyKey  string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTransactionRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *CreateTransactionRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *CreateTransactionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateTransactionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{11}
}

func (x *CreateTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// user_id is the ID of the user associated with the JWT token validated at the API Gateway
type GetTransactionsByAccountIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByAccountIdRequest) Reset() {
	*x = GetTransactionsByAccountIdRequest{}
	mi := &file_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByAccountIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByAccountIdRequest) ProtoMessage() {}

func (x *GetTransactionsByAccountIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByAccountIdRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsByAccountIdRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{12}
}

func (x *GetTransactionsByAccountIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTransactionsByAccountIdRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetTransactionsByAccountIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByAccountIdResponse) Reset() {
	*x = GetTransactionsByAccountIdResponse{}
	mi := &file_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByAccountIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByAccountIdResponse) ProtoMessage() {}

func (x *GetTransactionsByAccountIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByAccountIdResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsByAccountIdResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{13}
}

func (x *GetTransactionsByAccountIdResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// user_id is the ID of the user associated with the JWT token validated at the API Gateway
type ValidateAccountNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccountNumberRequest) Reset() {
	*x = ValidateAccountNumberRequest{}
	mi := &file_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccountNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccountNumberRequest) ProtoMessage() {}

func (x *ValidateAccountNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccountNumberRequest.ProtoReflect.Descriptor instead.
func (*ValidateAccountNumberRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{14}
}

func (x *ValidateAccountNumberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateAccountNumberRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

type ValidateAccountNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccountNumberResponse) Reset() {
	*x = ValidateAccountNumberResponse{}
	mi := &file_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccountNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccountNumberResponse) ProtoMessage() {}

func (x *ValidateAccountNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccountNumberResponse.ProtoReflect.Descriptor instead.
func (*ValidateAccountNumberResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateAccountNumberResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// user_id is the ID of the user associated with the JWT token validated at the API Gateway
type HasSufficientBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasSufficientBalanceRequest) Reset() {
	*x = HasSufficientBalanceRequest{}
	mi := &file_account_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasSufficientBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasSufficientBalanceRequest) ProtoMessage() {}

func (x *HasSufficientBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasSufficientBalanceRequest.ProtoReflect.Descriptor instead.
func (*HasSufficientBalanceRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{16}
}

func (x *HasSufficientBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HasSufficientBalanceRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *HasSufficientBalanceRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type HasSufficientBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sufficient    bool                   `protobuf:"varint,1,opt,name=sufficient,proto3" json:"sufficient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasSufficientBalanceResponse) Reset() {
	*x = HasSufficientBalanceResponse{}
	mi := &file_account_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasSufficientBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasSufficientBalanceResponse) ProtoMessage() {}

func (x *HasSufficientBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasSufficientBalanceResponse.ProtoReflect.Descriptor instead.
func (*HasSufficientBalanceResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{17}
}

func (x *HasSufficientBalanceResponse) GetSufficient() bool {
	if x != nil {
		return x.Sufficient
	}
	return false
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\x12\x05proto\x1a\x1bbuf/validate/validate.proto\"\x82\x01\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\xed\x01\n" +
	"\vTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12)\n" +
	"\x10transaction_type\x18\x05 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vtransfer_id\x18\a \x01(\tR\n" +
	"transferId\"\x86\x01\n" +
	"\x14CreateAccountRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x121\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eidempotencyKey\"6\n" +
	"\x15CreateAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"?\n" +
	"\x1aGetAccountsByUserIdRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\"I\n" +
	"\x1bGetAccountsByUserIdResponse\x12*\n" +
	"\baccounts\x18\x01 \x03(\v2\x0e.proto.AccountR\baccounts\"l\n" +
	" GetAccountByAccountNumberRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\"M\n" +
	"!GetAccountByAccountNumberResponse\x12(\n" +
	"\aaccount\x18\x01 \x01(\v2\x0e.proto.AccountR\aaccount\"\xa2\x01\n" +
	"#DeleteAccountByAccountNumberRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x121\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eidempotencyKey\"&\n" +
	"$DeleteAccountByAccountNumberResponse\"\x95\x02\n" +
	"\x18CreateTransactionRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12'\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12)\n" +
	"\x10transaction_type\x18\x04 \x01(\tR\x0ftransactionType\x12\x1f\n" +
	"\vtransfer_id\x18\x05 \x01(\tR\n" +
	"transferId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x121\n" +
	"\x0fidempotency_key\x18\a \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eidempotencyKey\"B\n" +
	"\x19CreateTransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"o\n" +
	"!GetTransactionsByAccountIdRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12'\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\taccountId\"\\\n" +
	"\"GetTransactionsByAccountIdResponse\x126\n" +
	"\ftransactions\x18\x01 \x03(\v2\x12.proto.TransactionR\ftransactions\"h\n" +
	"\x1cValidateAccountNumberRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\"5\n" +
	"\x1dValidateAccountNumberResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\"\x7f\n" +
	"\x1bHasSufficientBalanceRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\">\n" +
	"\x1cHasSufficientBalanceResponse\x12\x1e\n" +
	"\n" +
	"sufficient\x18\x01 \x01(\bR\n" +
	"sufficient2\xc3\x06\n" +
	"\x0eAccountService\x12L\n" +
	"\rCreateAccount\x12\x1b.proto.CreateAccountRequest\x1a\x1c.proto.CreateAccountResponse\"\x00\x12^\n" +
	"\x13GetAccountsByUserId\x12!.proto.GetAccountsByUserIdRequest\x1a\".proto.GetAccountsByUserIdResponse\"\x00\x12p\n" +
	"\x19GetAccountByAccountNumber\x12'.proto.GetAccountByAccountNumberRequest\x1a(.proto.GetAccountByAccountNumberResponse\"\x00\x12y\n" +
	"\x1cDeleteAccountByAccountNumber\x12*.proto.DeleteAccountByAccountNumberRequest\x1a+.proto.DeleteAccountByAccountNumberResponse\"\x00\x12X\n" +
	"\x11CreateTransaction\x12\x1f.proto.CreateTransactionRequest\x1a .proto.CreateTransactionResponse\"\x00\x12s\n" +
	"\x1aGetTransactionsByAccountId\x12(.proto.GetTransactionsByAccountIdRequest\x1a).proto.GetTransactionsByAccountIdResponse\"\x00\x12d\n" +
	"\x15ValidateAccountNumber\x12#.proto.ValidateAccountNumberRequest\x1a$.proto.ValidateAccountNumberResponse\"\x00\x12a\n" +
	"\x14HasSufficientBalance\x12\".proto.HasSufficientBalanceRequest\x1a#.proto.HasSufficientBalanceResponse\"\x00BV\n" +
	"\tcom.protoB\fAccountProtoP\x01Z\a.;proto\xa2\x02\x03PXX\xaa\x02\x05Proto\xca\x02\x05Proto\xe2\x02\x11Proto\\GPBMetadata\xea\x02\x05Protob\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_account_proto_goTypes = []any{
	(*Account)(nil),                              // 0: proto.Account
	(*Transaction)(nil),                          // 1: proto.Transaction
	(*CreateAccountRequest)(nil),                 // 2: proto.CreateAccountRequest
	(*CreateAccountResponse)(nil),                // 3: proto.CreateAccountResponse
	(*GetAccountsByUserIdRequest)(nil),           // 4: proto.GetAccountsByUserIdRequest
	(*GetAccountsByUserIdResponse)(nil),          // 5: proto.GetAccountsByUserIdResponse
	(*GetAccountByAccountNumberRequest)(nil),     // 6: proto.GetAccountByAccountNumberRequest
	(*GetAccountByAccountNumberResponse)(nil),    // 7: proto.GetAccountByAccountNumberResponse
	(*DeleteAccountByAccountNumberRequest)(nil),  // 8: proto.DeleteAccountByAccountNumberRequest
	(*DeleteAccountByAccountNumberResponse)(nil), // 9: proto.DeleteAccountByAccountNumberResponse
	(*CreateTransactionRequest)(nil),             // 10: proto.CreateTransactionRequest
	(*CreateTransactionResponse)(nil),            // 11: proto.CreateTransactionResponse
	(*GetTransactionsByAccountIdRequest)(nil),    // 12: proto.GetTransactionsByAccountIdRequest
	(*GetTransactionsByAccountIdResponse)(nil),   // 13: proto.GetTransactionsByAccountIdResponse
	(*ValidateAccountNumberRequest)(nil),         // 14: proto.ValidateAccountNumberRequest
	(*ValidateAccountNumberResponse)(nil),        // 15: proto.ValidateAccountNumberResponse
	(*HasSufficientBalanceRequest)(nil),          // 16: proto.HasSufficientBalanceRequest
	(*HasSufficientBalanceResponse)(nil),         // 17: proto.HasSufficientBalanceResponse
}
var file_account_proto_depIdxs = []int32{
	0,  // 0: proto.GetAccountsByUserIdResponse.accounts:type_name -> proto.Account
	0,  // 1: proto.GetAccountByAccountNumberResponse.account:type_name -> proto.Account
	1,  // 2: proto.GetTransactionsByAccountIdResponse.transactions:type_name -> proto.Transaction
	2,  // 3: proto.AccountService.CreateAccount:input_type -> proto.CreateAccountRequest
	4,  // 4: proto.AccountService.GetAccountsByUserId:input_type -> proto.GetAccountsByUserIdRequest
	6,  // 5: proto.AccountService.GetAccountByAccountNumber:input_type -> proto.GetAccountByAccountNumberRequest
	8,  // 6: proto.AccountService.DeleteAccountByAccountNumber:input_type -> proto.DeleteAccountByAccountNumberRequest
	10, // 7: proto.AccountService.CreateTransaction:input_type -> proto.CreateTransactionRequest
	12, // 8: proto.AccountService.GetTransactionsByAccountId:input_type -> proto.GetTransactionsByAccountIdRequest
	14, // 9: proto.AccountService.ValidateAccountNumber:input_type -> proto.ValidateAccountNumberRequest
	16, // 10: proto.AccountService.HasSufficientBalance:input_type -> proto.HasSufficientBalanceRequest
	3,  // 11: proto.AccountService.CreateAccount:output_type -> proto.CreateAccountResponse
	5,  // 12: proto.AccountService.GetAccountsByUserId:output_type -> proto.GetAccountsByUserIdResponse
	7,  // 13: proto.AccountService.GetAccountByAccountNumber:output_type -> proto.GetAccountByAccountNumberResponse
	9,  // 14: proto.AccountService.DeleteAccountByAccountNumber:output_type -> proto.DeleteAccountByAccountNumberResponse
	11, // 15: proto.AccountService.CreateTransaction:output_type -> proto.CreateTransactionResponse
	13, // 16: proto.AccountService.GetTransactionsByAccountId:output_type -> proto.GetTransactionsByAccountIdResponse
	15, // 17: proto.AccountService.ValidateAccountNumber:output_type -> proto.ValidateAccountNumberResponse
	17, // 18: proto.AccountService.HasSufficientBalance:output_type -> proto.HasSufficientBalanceResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
