<script lang="ts">
    import { authStore } from '$lib/stores/auth.svelte';
    import Button from '$lib/components/ui/Button.svelte';

    const isAuthenticated = $derived(authStore.isAuthenticated);
</script>

<svelte:head>
    <title>Banking App</title>
    <meta name="description" content="Modern banking application with microservices" />
</svelte:head>

<div class="hero-container">
    <div class="hero-content">
        <h1 class="hero-title">
            Minimalist Banking App
        </h1>
        <p class="hero-description">
            <em>Frontend's ugly because I was doing real work.</em><br>
            <em>The CSS? Autogenerated - the only rational way to write it without losing your damn mind.</em><br>
            <span style="opacity: 0.8;">Besides, <code>node_modules</code> has a family to feed!</span>

        </p>

        
        <div class="hero-actions">
            {#if isAuthenticated}
                <Button onclick={() => window.location.href = '/dashboard'}>
                    Go to Dashboard
                </Button>
            {:else}
                <Button onclick={() => window.location.href = '/login'}>
                    Get Started
                </Button>
                <Button 
                    variant="outline" 
                    onclick={() => window.location.href = '/register'}
                >
                    Create Account
                </Button>
            {/if}
        </div>
    </div>
</div>

<style>
    @reference "../app.css";

    .hero-container {
        @apply max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12;
    }

    .hero-content {
        @apply text-center;
    }

    .hero-title {
        @apply text-4xl font-bold text-gray-900 sm:text-6xl;
    }

    .hero-description {
        @apply mt-6 text-lg leading-8 text-gray-600;
    }

    .hero-actions {
        @apply mt-10 flex items-center justify-center gap-x-6;
    }
</style>