// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Account struct {
	ID            uuid.UUID    `json:"id"`
	UserID        string       `json:"user_id"`
	AccountNumber int64        `json:"account_number"`
	Balance       int64        `json:"balance"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}
