// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: account/proto/account_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     []byte                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	UserId        []byte                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_account_proto_account_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *Account) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *Account) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   []byte                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccountId       []byte                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount          int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp       int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TransactionType []byte                 `protobuf:"bytes,5,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"` // "credit" or "debit"
	Status          []byte                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                          // "pending", "completed", "failed"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_account_proto_account_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetTransactionId() []byte {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

func (x *Transaction) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetTransactionType() []byte {
	if x != nil {
		return x.TransactionType
	}
	return nil
}

func (x *Transaction) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []byte                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_account_proto_account_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *CreateAccountRequest) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type CreateAcocuntResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         []byte                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	AccountId     []byte                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAcocuntResponse) Reset() {
	*x = CreateAcocuntResponse{}
	mi := &file_account_proto_account_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAcocuntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAcocuntResponse) ProtoMessage() {}

func (x *CreateAcocuntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAcocuntResponse.ProtoReflect.Descriptor instead.
func (*CreateAcocuntResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAcocuntResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateAcocuntResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CreateAcocuntResponse) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

type GetAccountsByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []byte                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsByUserIdRequest) Reset() {
	*x = GetAccountsByUserIdRequest{}
	mi := &file_account_proto_account_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsByUserIdRequest) ProtoMessage() {}

func (x *GetAccountsByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetAccountsByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountsByUserIdRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

type GetAccountsByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         []byte                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Accounts      []*Account             `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsByUserIdResponse) Reset() {
	*x = GetAccountsByUserIdResponse{}
	mi := &file_account_proto_account_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsByUserIdResponse) ProtoMessage() {}

func (x *GetAccountsByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetAccountsByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountsByUserIdResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetAccountsByUserIdResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetAccountsByUserIdResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type CreateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountId       []byte                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount          int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionType []byte                 `protobuf:"bytes,3,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"` // "credit" or "debit"
	Status          []byte                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                          // "pending", "completed", "failed"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_account_proto_account_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTransactionRequest) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *CreateTransactionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetTransactionType() []byte {
	if x != nil {
		return x.TransactionType
	}
	return nil
}

func (x *CreateTransactionRequest) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         []byte                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	TransactionId []byte                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_account_proto_account_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTransactionResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateTransactionResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CreateTransactionResponse) GetTransactionId() []byte {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

type GetTransactionsByAccountIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     []byte                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByAccountIdRequest) Reset() {
	*x = GetTransactionsByAccountIdRequest{}
	mi := &file_account_proto_account_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByAccountIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByAccountIdRequest) ProtoMessage() {}

func (x *GetTransactionsByAccountIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByAccountIdRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsByAccountIdRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransactionsByAccountIdRequest) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

type GetTransactionsByAccountIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         []byte                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByAccountIdResponse) Reset() {
	*x = GetTransactionsByAccountIdResponse{}
	mi := &file_account_proto_account_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByAccountIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByAccountIdResponse) ProtoMessage() {}

func (x *GetTransactionsByAccountIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_account_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByAccountIdResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsByAccountIdResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_account_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetTransactionsByAccountIdResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetTransactionsByAccountIdResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetTransactionsByAccountIdResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_account_proto_account_service_proto protoreflect.FileDescriptor

const file_account_proto_account_service_proto_rawDesc = "" +
	"\n" +
	"#account/proto/account_service.proto\"\x82\x01\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\fR\taccountId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x03R\raccountNumber\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\fR\x06userId\"\xcc\x01\n" +
	"\vTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\fR\rtransactionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\fR\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12)\n" +
	"\x10transaction_type\x18\x05 \x01(\fR\x0ftransactionType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\fR\x06status\"I\n" +
	"\x14CreateAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\fR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\"d\n" +
	"\x15CreateAcocuntResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\fR\x05error\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\fR\taccountId\"5\n" +
	"\x1aGetAccountsByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\fR\x06userId\"q\n" +
	"\x1bGetAccountsByUserIdResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\fR\x05error\x12$\n" +
	"\baccounts\x18\x03 \x03(\v2\b.AccountR\baccounts\"\x94\x01\n" +
	"\x18CreateTransactionRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\fR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12)\n" +
	"\x10transaction_type\x18\x03 \x01(\fR\x0ftransactionType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\fR\x06status\"p\n" +
	"\x19CreateTransactionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\fR\x05error\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\fR\rtransactionId\"B\n" +
	"!GetTransactionsByAccountIdRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\fR\taccountId\"\x84\x01\n" +
	"\"GetTransactionsByAccountIdResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\fR\x05error\x120\n" +
	"\ftransactions\x18\x03 \x03(\v2\f.TransactionR\ftransactions2\xdd\x02\n" +
	"\x0eAccountService\x12@\n" +
	"\rCreateAccount\x12\x15.CreateAccountRequest\x1a\x16.CreateAcocuntResponse\"\x00\x12R\n" +
	"\x13GetAccountsByUserId\x12\x1b.GetAccountsByUserIdRequest\x1a\x1c.GetAccountsByUserIdResponse\"\x00\x12L\n" +
	"\x11CreateTransaction\x12\x19.CreateTransactionRequest\x1a\x1a.CreateTransactionResponse\"\x00\x12g\n" +
	"\x1aGetTransactionsByAccountId\x12\".GetTransactionsByAccountIdRequest\x1a#.GetTransactionsByAccountIdResponse\"\x00B\tZ\a./protob\x06proto3"

var (
	file_account_proto_account_service_proto_rawDescOnce sync.Once
	file_account_proto_account_service_proto_rawDescData []byte
)

func file_account_proto_account_service_proto_rawDescGZIP() []byte {
	file_account_proto_account_service_proto_rawDescOnce.Do(func() {
		file_account_proto_account_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_account_service_proto_rawDesc), len(file_account_proto_account_service_proto_rawDesc)))
	})
	return file_account_proto_account_service_proto_rawDescData
}

var file_account_proto_account_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_account_proto_account_service_proto_goTypes = []any{
	(*Account)(nil),                            // 0: Account
	(*Transaction)(nil),                        // 1: Transaction
	(*CreateAccountRequest)(nil),               // 2: CreateAccountRequest
	(*CreateAcocuntResponse)(nil),              // 3: CreateAcocuntResponse
	(*GetAccountsByUserIdRequest)(nil),         // 4: GetAccountsByUserIdRequest
	(*GetAccountsByUserIdResponse)(nil),        // 5: GetAccountsByUserIdResponse
	(*CreateTransactionRequest)(nil),           // 6: CreateTransactionRequest
	(*CreateTransactionResponse)(nil),          // 7: CreateTransactionResponse
	(*GetTransactionsByAccountIdRequest)(nil),  // 8: GetTransactionsByAccountIdRequest
	(*GetTransactionsByAccountIdResponse)(nil), // 9: GetTransactionsByAccountIdResponse
}
var file_account_proto_account_service_proto_depIdxs = []int32{
	0, // 0: GetAccountsByUserIdResponse.accounts:type_name -> Account
	1, // 1: GetTransactionsByAccountIdResponse.transactions:type_name -> Transaction
	2, // 2: AccountService.CreateAccount:input_type -> CreateAccountRequest
	4, // 3: AccountService.GetAccountsByUserId:input_type -> GetAccountsByUserIdRequest
	6, // 4: AccountService.CreateTransaction:input_type -> CreateTransactionRequest
	8, // 5: AccountService.GetTransactionsByAccountId:input_type -> GetTransactionsByAccountIdRequest
	3, // 6: AccountService.CreateAccount:output_type -> CreateAcocuntResponse
	5, // 7: AccountService.GetAccountsByUserId:output_type -> GetAccountsByUserIdResponse
	7, // 8: AccountService.CreateTransaction:output_type -> CreateTransactionResponse
	9, // 9: AccountService.GetTransactionsByAccountId:output_type -> GetTransactionsByAccountIdResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_account_proto_account_service_proto_init() }
func file_account_proto_account_service_proto_init() {
	if File_account_proto_account_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_account_service_proto_rawDesc), len(file_account_proto_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_proto_account_service_proto_goTypes,
		DependencyIndexes: file_account_proto_account_service_proto_depIdxs,
		MessageInfos:      file_account_proto_account_service_proto_msgTypes,
	}.Build()
	File_account_proto_account_service_proto = out.File
	file_account_proto_account_service_proto_goTypes = nil
	file_account_proto_account_service_proto_depIdxs = nil
}
