// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Transfer struct {
	ID             uuid.UUID    `json:"id"`
	IdempotencyKey string       `json:"idempotency_key"`
	FromAccountID  uuid.UUID    `json:"from_account_id"`
	ToAccountID    uuid.UUID    `json:"to_account_id"`
	Amount         int64        `json:"amount"`
	Status         string       `json:"status"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
}
